#32 PostgreSQL 인덱스 리스트 API 생성
junhkang/spectra pull request #39
Opened 2024-06-19 13:42 UTC by SEAN-Leeeee

## 관련 이슈 (Related Issues)

 #32

- 관련 이슈 1 (#32)
## 설명 (Description)

PostgreSQL 데이터베이스에서 인덱스 전체 리스트를 가져와 해당 정보를 노출시키는 백엔드 API를 생성합니다.
PostgreSQL 데이터베이스에서 인덱스 리스트를 가져오는 쿼리 작성 및 페이징 처리를 구현합니다.

## 변경 사항 (Changes)

- monitoringMapper.xml에 pg_indexes 테이블에서 인덱스 정보를 조회하는 쿼리 추가
- "/all-indexes"경로로 GetMapping을 받아 인덱스 리스트를 리턴하는 코드 추가
- MonitoringServiceTest에 테스트 추가. 

## 체크리스트 (Checklist)

- [x ] 코드가 제대로 동작하는지 테스트했습니다.  
 -> 프로젝트 설정의 문제인지, 의존성의 문제인지 테스트 코드는 작동되지 않고있습니다. 참고한 shouldSelectUnusedIndexList() 테스트도 fail이 되고있어서 일단 같은 내용으로 작성하여 커밋했습니다. 제가 해결할 수 있는 부분이 있을까요?

- [x] 문서를 적절하게 업데이트했습니다.
-> 제가 업데이트해야 하는 문서가 있다면 말씀 부탁드립니다!

2024-06-19 14:57 UTC, junhkang requested changes

2024-06-19 14:57 UTC, junhkang commented on src/main/resources/mapper/postgres/MonitoringMapper.xml
> +    <select id="getAllIndexesList" resultType="IndexDTO">
parameterType을 추가해주실 수 있을까요?

샘플 매퍼에 누락되어서 추가해 놓았습니다. #41

2024-06-19 14:57 UTC, junhkang commented on src/test/java/com/example/spectra/service/MonitoringServiceTest.java
> +        assertEquals(allIndexesList.size(), Constants.PAGE_SIZE);
데이터베이스 직접 접근하여 작동하는 테스트케이스는 Mock 접속 정보를 곧 올려 두겠습니다.

일단 테스트코드는 문제 없어 보여서 그대로 올려주시고
테스트 시나리오가 확정되면 기여 가이드에 상세 가이드 업로드하도록 하겠습니다.

2024-06-23 11:52 UTC, SEAN-Leeeee commented on src/test/java/com/example/spectra/service/MonitoringServiceTest.java
> +        assertEquals(allIndexesList.size(), Constants.PAGE_SIZE);
죄송해요 몸이 안 좋아서 수정이 늦었습니다!

2024-06-24 00:24 UTC, junhkang approved these changes

2024-06-24 00:25 UTC, merged